server {
    listen 80;

    # Проксируем весь трафик в контейнер приложения. Сервис в compose называется api,
    # внутри сети reviews-service доступен по этому имени на порту 8080.
    location / {
        proxy_pass http://api:8080;
    }
}
